import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";
import { Cormorant_Garamond } from "next/font/google";
import ScrollToTop from "@/myComponents/ScrolltoTop";
import WhatsAppButton from "@/myComponents/Whatsapp";

export const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});
export const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"], // This ensures italic variants are loaded
  variable: "--font-cormorant", // Define a CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${cormorant.variable} h-full antialiased max-w-xl mx-auto`}
    >
      <body className="min-h-full flex flex-col">
       
        {children}
      </body>
    </html>
  );
}
